# Generated by Django 3.2 on 2022-09-29 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=10)),
                ('valor', models.CharField(max_length=10)),
                ('descrição', models.CharField(max_length=50)),
                ('quantidade', models.CharField(max_length=50)),
            ],
        ),
    ]
